# Generated by Django 2.2.5 on 2019-09-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_set',
        ),
        migrations.AddField(
            model_name='cardset',
            name='card',
            field=models.ManyToManyField(to='accounts.Card'),
        ),
    ]
